name = "fastapi"
compatibility_date = "2024-4-08"

[vars]
UPSTASH_REDIS_REST_URL = "https://ideal-hawk-44825.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "Aa8ZASQgYjdkMjE4MzktNGQwNS00MTg3LTkwYWEtNDViOTEzN2Q0NWZiMDMzOTAxMDNkM2M0NDQ0Mjk3MmQzZjI3MThmNzQyODc="